### ISSUE TITLE
The plugins  `hexcolor` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by DevTiago** [ggichure/hexcolor#10]
Hey there,

First of all thanks for the package, really useful.

I'm using it for a long time, but today i've checked this warning:

**_The plugins `hexcolor` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration._**

I don't know if this is a package issue or something with my project.

Appreciate your comments.

**Comment by ggichure** [comment]
the project is already using flutter embedding 2
