### ISSUE TITLE
Changelog is reversed 

### ISSUE THREAD

**Issue by guyluz11** [ggichure/hexcolor#11]
[changelog](https://pub.dev/packages/hexcolor/changelog) is reversed 
![image](https://user-images.githubusercontent.com/9304740/129979491-cc97c658-cec3-4bad-80d3-69481a1fe4e8.png)
The newest should be in the top.

Can I create pull request with [CHANGELOG.md](https://github.com/ggichure/hexcolor/blob/master/CHANGELOG.md) lines reversed ?.

**Comment by ggichure** [comment]
sure. thanks

**Comment by guyluz11** [comment]
Thanks.
