### ISSUE TITLE
Why is this a plugin?

### ISSUE THREAD

**Issue by bartekpacia** [ggichure/hexcolor#14]
Looks like no functionality of the underlying platform is need at all.

**Comment by ggichure** [comment]
> hexcolor plugin allows you to use hex color codes in your flutter projects

Worked on  this (Mainly from SO)  as part of my deep dive into flutter, people liked and used it  and as such I'm obliged to maintain it .

**Comment by bartekpacia** [comment]
yeah sure I understand, but this could be just a plain Dart package, not a plugin with native code in it

**Comment by ggichure** [comment]
ok noted. I'll implement in the next update.

**Comment by bartekpacia** [comment]
thanks :)
