### ISSUE TITLE
Is hexcolor dart a native package?

### ISSUE THREAD

**Issue by guyluz11** [ggichure/hexcolor#18]
It is written in the change log that hexcolor has become a dart native package but pub.dev does not show that

![image](https://user-images.githubusercontent.com/9304740/206985760-ac922e2e-f0e9-4af0-b5f0-dbca7011474d.png)

**Comment by ggichure** [comment]
Yes its a native dart package. I'll check my pub configs

**Comment by guyluz11** [comment]
This part is auto-generated by pub.dev, so if you are importing any flutter package or using dart built in flutter package like dart:UI it will show it as flutter only

![image](https://user-images.githubusercontent.com/9304740/206999187-e05d5281-f142-409e-827c-ed41768c04b7.png)
