### ISSUE TITLE
Kotlin version of the HexColor plugin needs to be updated.

### ISSUE THREAD

**Issue by shakaib-developer** [ggichure/hexcolor#19]
I am getting this error while running flutter app on Android. On iOS it's working fine.

<img width="676" alt="Screenshot 2023-11-20 at 9 36 06 PM" src="https://github.com/ggichure/hexcolor/assets/53529523/8b20cc54-90bf-4072-875e-346cd7656af9">

**Comment by ggichure** [comment]
`HexColor` is a dart package from `3.0.0` you shouldn't be getting this. What version are you running?

**Comment by shakaib-developer** [comment]
I don't know. In my pubspec only package name is written, like this.
hexcolor: 
May be it takes the latest version ?

**Comment by ggichure** [comment]
It takes what 'works' with the other packages. try 
`hexcolor: ^3.0.0`

Edit:
This assumes you are running a project with null safety .

**Comment by shakaib-developer** [comment]
It worked. Thanks!
