### ISSUE TITLE
Hexcolor no longer work on Flutter 1.22.1 • channel stable

### ISSUE THREAD

**Issue by muktabd** [ggichure/hexcolor#4]
After update my flutter into 1.22.1 in stable channel hexcolor is not working. I try pub get, pub upgrade, run flutter doctor but still remain the problem and I didn't see any issue in flutter doctor.

C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.1, on Microsoft Windows [Version 10.0.18363.1082], locale en-US)
    • Flutter version 1.22.1 at C:\src\flutter
    • Framework revision f30b7f4db9 (4 days ago), 2020-10-08 10:06:30 -0700
    • Engine revision 75bef9f6c8
    • Dart version 2.10.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\ProgramFiles\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = D:\ProgramFiles\Sdk
    • Java binary at: D:\ProgramFiles\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\ProgramFiles\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\RBFBD LTD\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • HTC One M9 (mobile) • HC4BRYC12938 • android-arm64 • Android 6.0 (API 23)

• No issues found!
Process finished with exit code 0

**Comment by ggichure** [comment]
sorry about that, I'm on master channel ,let me switch to stable and publish else use [1.0.4](https://pub.dev/packages/hexcolor/versions/1.0.4)

**Comment by engr-muktaahmed** [comment]
For now using 1.0.4. When you done will use stable again. But thanks for quick response.

**Comment by ggichure** [comment]
just released 1.0.6

**Comment by engr-muktaahmed** [comment]
That's great. Thanks a lot..
