### ISSUE TITLE
Error: The method 'Hexcolor' isn't defined for the class 'AddCommissionScreenState'.

### ISSUE THREAD

**Issue by Bharavi26** [ggichure/hexcolor#9]
Try correcting the name to the name of an existing method, or defining a method named 'Hexcolor'.

Flutter Doctor
----------------

[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.1083], locale en-US)
    • Flutter version 2.0.3 at F:\flutter_sdk\flutter
    • Framework revision 4d7946a68d (4 months ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at \AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = \AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = \AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.58.0)
    • VS Code at \AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.24.0

[√] Connected device (4 available)
    • vivo 1818 (mobile)                 • d14b5985      • android-arm64  • Android 11 (API 30)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
Process finished with exit code 0

**Comment by ggichure** [comment]
For Android ,iOS ,Mac,windows ,Linux it's HexColor whilst for web it's hexcolor .
